import { Footer, Navbar, Sidebar } from '@/components';
import './globals.css';
import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.className} flex flex-col justify-between min-h-screen`}
      >
        <header>
          <Navbar />
        </header>
        <div className="grid flex-grow grid-cols-2">
          <aside>
            <Sidebar />
          </aside>
          <main>{children}</main>
        </div>
        <footer className="p-2 dark:bg-neutral-900 bg-neutral-300">
          <Footer />
        </footer>
      </body>
    </html>
  );
}

export { RootLayout as default, metadata };
